config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticate :user, lambda { |u| u.admin? } do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end

  #resources :camera_event_assets
  resources :camera_events do
    collection do
      get '/kept' => 'camera_events#kept'
      get :selected_from_timeline
    end

    member do
      post 'keep' => 'camera_events#keep'
      post 'unkeep' => 'camera_events#unkeep'
    end
  end
  resources :cameras do
    member do
      get :preview
    end
    collection do
      get :live
      get :live_focus
      put :live_focus, action: 'update_live_focus'
    end
  end

  resource :cron, controller: 'cron' do
    post :mark_events_as_failed
    post :clean_tempfiles
    post :purge_old_events
    post :find_new_motion_events
    post :perform_remote_cleanup
  end

  namespace :admin do
    resources :cameras do
      member do
        post :move_higher
        post :move_lower
      end
      resource :stats, controller: 'cameras/stats'
    end
    resources :users
    resources :system_settings, path: 'settings', only: [:index] do
      collection do
        patch :update
        post :reboot
      end
    end
    resources :stats
  end


  root 'cameras#live'

end

app/controllers/admin/cameras/stats_controller.rb
class Admin::Cameras::StatsController < Admin::BaseController
  def show
    @camera = Camera.find(params[:camera_id])
    oldest_event_timestamp = CameraEvent.ordered.unkept.where.not(event_timestamp: nil).last.event_timestamp || 30.days.ago
    @grouped_events = @camera.camera_events.group_by_day(:event_timestamp, range: (oldest_event_timestamp..Time.now), format: "%m-%d").count
    @grouped_event_storage = CameraEventAsset
      .joins(:camera_event)
      .where(camera_events: { camera_id: @camera.id })
      .group_by_day(:event_timestamp, range: (oldest_event_timestamp..Time.now), format: "%m-%d")
      .sum(:asset_size)
      .map{ |k, v| [k, (v.to_f / 1.megabyte).round]}
      .to_h
  end
end

app/controllers/admin/stats_controller.rb
class Admin::StatsController < Admin::BaseController
  def index
    @storage_per_camera = CameraEventAsset.joins(:camera_event).group('camera_events.camera_id').sum(:asset_size)
    oldest_event_timestamp = CameraEvent.ordered.unkept.where.not(event_timestamp: nil).last.event_timestamp || 30.days.ago
    @grouped_events = CameraEvent.group_by_day(:event_timestamp, range: (oldest_event_timestamp..Time.now), format: "%m-%d").count
    @grouped_event_storage = CameraEventAsset
      .joins(:camera_event)
      .group_by_day(:event_timestamp, range: (oldest_event_timestamp..Time.now), format: "%m-%d")
      .sum(:asset_size)
      .map{ |k, v| [k, (v.to_f / 1.megabyte).round]}
      .to_h
  end
end

app/views/admin/stats/index.haml
.row
  .col-md-6
    %h1 Storage
    %table.table.table-striped
      %tr
        %th Camera
        %th Storage
      - Camera.ordered.each do |camera|
        %tr
          %th= link_to camera.name, admin_camera_stats_path(camera)
          %td= number_to_human_size(@storage_per_camera[camera.id] || 0)
      %tr
        %th Total
        %td= number_to_human_size CameraEventAsset.sum(:asset_size)
    %h4 MB Per Day
    = column_chart @grouped_event_storage, library: {groupByRowLabel: false }

  .col-md-6
    %h1 Events
    %table.table.table-striped
      %tr
        %th Camera
        %th Events
        %th Kept Events
      - Camera.ordered.each do |camera|
        %tr
          %th= camera.name
          %td= camera.camera_events.count
          %td= camera.camera_events.kept.count
      %tr
        %th Total
        %td= CameraEvent.count
    %h4 Events Per Day
    = column_chart @grouped_events, library: {groupByRowLabel: false }