config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticate :user, lambda { |u| u.admin? } do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end

  #resources :camera_event_assets
  resources :camera_events do
    collection do
      get '/kept' => 'camera_events#kept'
      get :selected_from_timeline
    end

    member do
      post 'keep' => 'camera_events#keep'
      post 'unkeep' => 'camera_events#unkeep'
    end
  end
  resources :cameras do
    member do
      get :preview
    end
    collection do
      get :live
      get :live_focus
      put :live_focus, action: 'update_live_focus'
    end
  end

  resource :cron, controller: 'cron' do
    post :mark_events_as_failed
    post :clean_tempfiles
    post :purge_old_events
    post :find_new_motion_events
    post :perform_remote_cleanup
  end

  namespace :admin do
    resources :cameras do
      member do
        post :move_higher
        post :move_lower
      end
      resource :stats, controller: 'cameras/stats'
    end
    resources :users
    resources :system_settings, path: 'settings', only: [:index] do
      collection do
        patch :update
        post :reboot
      end
    end
    resources :stats
  end


  root 'cameras#live'

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}/
    %title=content_for?(:page_title) ? content_for(:page_title) : "Great Eye"

    =# raw "<link href=\"http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,600,700,300&subset=latin\" rel=\"stylesheet\" type=\"text/css\">"

    = stylesheet_link_tag    "application", :media => "all", data: { turbolinks_track: true }
    = javascript_include_tag "application", data: { turbolinks_track: true }
    = javascript_include_tag "https://www.gstatic.com/charts/loader.js"

    %link{rel: "apple-touch-icon", href: image_path("great-eye-sm.jpg")}

    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/

    = csrf_meta_tags
  %body.body{ class: content_for?(:body_class) ? content_for(:body_class) : "" }
    - if params[:kiosk] != "true"
      %nav.navbar.navbar-default{ "role" => "navigation" }
        .container-fluid
          .navbar-header
            %button.navbar-toggle{ "type" => "button", "data-toggle" => "collapse", "data-target" => ".bs-navbar-collapse"}
              %span.sr-only
                Toggle Navigation
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            %a.navbar-brand{:href => "/"}
              %img{ src: image_path("great-eye-sm.jpg"), style: "max-height: 40px; margin-top: -10px; border-radius: 5px", alt: "Great Eye", align: "left" }
          %nav.collapse.navbar-collapse.bs-navbar-collapse
            %ul.nav.navbar-nav
              - cn = controller.controller_name

              %li{:class => cn == 'cameras' ? 'active' : ''}
                = link_to "Cameras", cameras_path

              %li{:class => (cn == 'camera_events' && controller.action_name == "index") ? 'active' : ''}
                = link_to "Recent Events", camera_events_path

              %li{:class => (cn == 'camera_events' && controller.action_name == "kept") ? 'active' : ''}
                = link_to "Kept Events", kept_camera_events_path

            - if current_user&.admin?
              %ul.nav.navbar-nav.navbar-right
                %li.dropdown
                  %a.dropdown-toggle{href: '#', data: {toggle: 'dropdown'} , role: 'button'} Admin
                  %ul.dropdown-menu
                    %li
                      = link_to "Users", admin_users_path
                      = link_to "Cameras", admin_cameras_path
                      = link_to "Settings", admin_system_settings_path
                      = link_to "Stats", admin_stats_path
                      = link_to "Sidekiq", sidekiq_web_path


    .container-fluid
      = render partial: 'shared/notices'
      = yield